Description: cfn-certificate-provider pipeline
Parameters: 
  GithubAccessToken:
    Type: String
    NoEcho: true
    Description: OAuth token for GitHub
  GithubUsername:
    Type: String
    Description: Github username containing the project's repository
    Default: sourceallies
  GithubRepository:
    Type: String
    Description: Github repository where the project is located
    Default: cfn-certificate-provider
  GithubBranch:
    Type: String
    Description: Github branch to track
    Default: master
Mappings:
  Accounts:
    Shared:
      Name: Shared
      Id: "018303830101"
      PipelineRoleArn: arn:aws:iam::018303830101:role/Pipeline
    Dev:
      Name: Dev
      Id: "729161019481"
      DeployerRoleArn: arn:aws:iam::729161019481:role/Deployer
    Prod:
      Name: Prod
      Id: "487696863217"
      DeployerRoleArn: arn:aws:iam::487696863217:role/Deployer
Conditions:
  InUsEast1:
    !Equals 
      - !Ref AWS::Region
      - us-east-1
Resources:
  ArtifactStore:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub cfn-certificate-provider-artifacts-${AWS::Region}
  ArtifactStorePolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ArtifactStore
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action: s3:*
            Resource:
              - !Sub arn:aws:s3:::${ArtifactStore}
              - !Sub arn:aws:s3:::${ArtifactStore}/*
            Principal:
              AWS:
                - !FindInMap [Accounts, Shared, PipelineRoleArn] 
                - !FindInMap [Accounts, Dev, DeployerRoleArn]
                - !FindInMap [Accounts, Prod, DeployerRoleArn]
  ArtifactKey: #Needed to allow Dev/Prod to decrypt artifacts in the Shared account's ArtifactStore
    Type: AWS::KMS::Key
    Properties:
      Description: Key used for encrypting artifacts
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - kms:*
            Resource: "*"
            Principal:
              AWS:
                - !FindInMap [Accounts, Shared, Id]
                - !FindInMap [Accounts, Dev, DeployerRoleArn]
                - !FindInMap [Accounts, Prod, DeployerRoleArn]
  ArtifactKeyAlias:
    Type: AWS::KMS::Alias
    Properties: 
      TargetKeyId: !Ref ArtifactKey
      AliasName: alias/cfn-certificate-provider-artifacts
  BranchedBuildProject:
    Type: AWS::CodeBuild::Project
    Condition: InUsEast1
    Properties:
      Name: !Sub ${AWS::StackName}-branched-build
      ServiceRole: !FindInMap [Accounts, Shared, PipelineRoleArn]
      EncryptionKey: !GetAtt ArtifactKey.Arn
      BadgeEnabled: true
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: !ImportValue aws-shared-services-pipeline-BuildEnvImage
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: ARTIFACT_STORE
            Value: !Ref ArtifactStore
      Cache:
        Type: LOCAL
        Modes:
          - LOCAL_CUSTOM_CACHE
          - LOCAL_DOCKER_LAYER_CACHE
      Source:
        Type: GITHUB
        Location: !Sub https://github.com/${GithubUsername}/${GithubRepository}.git
        ReportBuildStatus: true
      Artifacts:
        Type: NO_ARTIFACTS
      Triggers:
        Webhook: true
        FilterGroups:
          - - Pattern: ^refs/heads/master$
              ExcludeMatchedPattern: true
              Type: HEAD_REF
            - Pattern: PUSH,PULL_REQUEST_CREATED,PULL_REQUEST_UPDATED,PULL_REQUEST_REOPENED
              Type: EVENT
  BuildProject:
    Type: AWS::CodeBuild::Project
    Condition: InUsEast1
    Properties:
      Name: !Sub ${AWS::StackName}-build
      ServiceRole: !FindInMap [Accounts, Shared, PipelineRoleArn]
      EncryptionKey: !GetAtt ArtifactKey.Arn
      Cache:
        Type: LOCAL
        Modes:
          - LOCAL_CUSTOM_CACHE
          - LOCAL_DOCKER_LAYER_CACHE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: !ImportValue aws-shared-services-pipeline-BuildEnvImage
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: ARTIFACT_STORE
            Value: !Ref ArtifactStore
      Source:
        Type: CODEPIPELINE
      Artifacts:
        Type: CODEPIPELINE
  PipelineWebhook:
    Type: AWS::CodePipeline::Webhook
    Condition: InUsEast1
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: !Ref GithubAccessToken
      Filters:
        - JsonPath: $.ref
          MatchEquals: "refs/heads/{Branch}"
      TargetPipeline: !Ref Pipeline
      TargetAction: Source
      TargetPipelineVersion: !GetAtt Pipeline.Version
      RegisterWithThirdParty: true
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Condition: InUsEast1
    Properties:
      Name: !Ref AWS::StackName
      ArtifactStores:
        - Region: us-east-1
          ArtifactStore:
            Type: S3
            Location: cfn-certificate-provider-artifacts-us-east-1
            EncryptionKey:
              Id: !Sub arn:aws:kms:us-east-1:${AWS::AccountId}:alias/cfn-certificate-provider-artifacts
              Type: KMS
      RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/Pipeline
      RestartExecutionOnUpdate: true
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Provider: GitHub
                Owner: ThirdParty
                Version: 1
              OutputArtifacts:
                - Name: sourceCode
              Configuration:
                Owner: !Ref GithubUsername
                Repo: !Ref GithubRepository
                Branch: !Ref GithubBranch
                OAuthToken: !Ref GithubAccessToken
                PollForSourceChanges: false
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: sourceCode
              OutputArtifacts:
                - Name: buildResults
              Configuration:
                ProjectName: !Ref BuildProject
        - Name: Deploy_Shared
          Actions:
            - Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: buildResults
              Configuration:
                StackName: CfnCertificateProvider
                ActionMode: CREATE_UPDATE
                TemplatePath: buildResults::cloudformation.template.yml
                RoleArn: !FindInMap [Accounts, Shared, PipelineRoleArn]
                Capabilities: CAPABILITY_IAM
              RunOrder: 1
        - Name: Deploy_Dev
          Actions:
            - Name: UsEast1
              RoleArn: !FindInMap [Accounts, Dev, DeployerRoleArn]
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: buildResults
              Configuration:
                StackName: CfnCertificateProvider
                ActionMode: CREATE_UPDATE
                TemplatePath: buildResults::cloudformation.template.yml
                RoleArn: !FindInMap [Accounts, Dev, DeployerRoleArn]
                Capabilities: CAPABILITY_IAM
              RunOrder: 1
        - Name: Deploy_Prod
          Actions:
            - Name: Approve
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: 1
              InputArtifacts: []
              OutputArtifacts: []
              RunOrder: 1
            - Name: UsEast1
              RoleArn: !FindInMap [Accounts, Prod, DeployerRoleArn]
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: buildResults
              Configuration:
                StackName: CfnCertificateProvider
                ActionMode: CREATE_UPDATE
                TemplatePath: buildResults::cloudformation.template.yml
                RoleArn: !FindInMap [Accounts, Prod, DeployerRoleArn]
                Capabilities: CAPABILITY_IAM
              RunOrder: 2
