name: AWS Delete CfnCertificateProvider Stack
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Which source environment to use
        type: choice
        required: true
        options:
          - DEV
          - PROD

env:
  DEV: "arn:aws:iam::729161019481:role/Deployer"
  PROD: "arn:aws:iam::487696863217:role/Deployer"

permissions:
  id-token: write
  contents: read

jobs:
  delete-stack:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ env[inputs.environment] }}
          role-session-name: cfn-certificate-provider-delete-stack
          role-duration-seconds: 1200

      - name: Delete Stack
        run: aws cloudformation delete-stack --stack-name CfnCertificateProvider
